services:
  cache:
    container_name: "cache"
    image: "docker.io/library/redis:8.2"
    environment:
      REDIS_PASSWORD: "bwitanFqMa8ZlCcazDkJKw"
    ports:
    - target: 6379
      published: 6379
    command:
    - "redis-server"
    - "--requirepass"
    - "bwitanFqMa8ZlCcazDkJKw"
    restart: unless-stopped
  apiservice:
    container_name: "apiservice"
    image: "192.168.1.176:5000/apiservice:latest"
    environment:
      ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
      HTTP_PORTS: "8080"
      ConnectionStrings__cache: "cache:6379,password=bwitanFqMa8ZlCcazDkJKw"
      CACHE_HOST: "cache"
      CACHE_PORT: "6379"
      CACHE_PASSWORD: "bwitanFqMa8ZlCcazDkJKw"
      ASPNETCORE_ENVIRONMENT: Development
      Logging__FilePath: "/app/logs"
    ports:
    - target: 8080
      published: 10000
    - target: 8443
      published: 10001
    volumes:
    - /var/log/gridbot:/app/logs
    restart: unless-stopped
