services:
  aspire-dashboard:
    container_name: "aspire-dashboard"
    image: "mcr.microsoft.com/dotnet/aspire-dashboard:9.0"
    environment:
      DOTNET_DASHBOARD_UNSECURED_ALLOW_ANONYMOUS: "true"
    ports:
    - target: 18888
      published: 18888
    restart: unless-stopped
  cache:
    container_name: "cache"
    image: "docker.io/library/redis:8.2"
    environment:
      REDIS_PASSWORD: "bwitanFqMa8ZlCcazDkJKw"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://aspire-dashboard:18889"
      OTEL_SERVICE_NAME: "cache"
    ports:
    - target: 6379
      published: 6379
    command:
    - "redis-server"
    - "--requirepass"
    - "bwitanFqMa8ZlCcazDkJKw"
    restart: unless-stopped
  apiservice:
    container_name: "apiservice"
    image: "192.168.1.176:5000/apiservice:latest"
    environment:
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"
      ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
      HTTP_PORTS: "8080"
      ConnectionStrings__cache: "cache:6379,password=bwitanFqMa8ZlCcazDkJKw"
      CACHE_HOST: "cache"
      CACHE_PORT: "6379"
      CACHE_PASSWORD: "bwitanFqMa8ZlCcazDkJKw"
      CACHE_URI: "redis://:{cache-password-uri-encoded.value}@cache:6379"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://aspire-dashboard:18889"
      OTEL_SERVICE_NAME: "apiservice"
      ASPNETCORE_ENVIRONMENT: Development
    ports:
    - target: 8080
      published: 10000
    - target: 8443
      published: 10001
    restart: unless-stopped
  webfrontend:
    container_name: "webfrontend"
    image: "192.168.1.176:5000/webfrontend:latest"
    environment:
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"
      ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
      HTTP_PORTS: "8080"
      ConnectionStrings__cache: "cache:6379,password=bwitanFqMa8ZlCcazDkJKw"
      CACHE_HOST: "cache"
      CACHE_PORT: "6379"
      CACHE_PASSWORD: "bwitanFqMa8ZlCcazDkJKw"
      CACHE_URI: "redis://:{cache-password-uri-encoded.value}@cache:6379"
      APISERVICE_HTTP: "http://apiservice:8080"
      services__apiservice__http__0: "http://apiservice:8080"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://aspire-dashboard:18889"
      OTEL_SERVICE_NAME: "webfrontend"
      ASPNETCORE_ENVIRONMENT: Development
    ports:
    - target: 8080
      published: 10002
    - target: 8443
      published: 10003
    restart: unless-stopped
