<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\GridBot.ServiceDefaults\GridBot.ServiceDefaults.csproj" />
    <ProjectReference Include="..\GridBot.Web.Client\GridBot.Web.Client.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.StackExchange.Redis.OutputCaching" Version="13.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Server" Version="10.0.0-preview.5.25277.114" />
    <PackageReference Include="MudBlazor" Version="8.5.0" />
    <PackageReference Include="Yarp.ReverseProxy" Version="2.2.0" />
  </ItemGroup>

</Project>
