<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Native\signer-amd64.dll" />
  </ItemGroup>


  <ItemGroup>
    <ProjectReference Include="..\GridBot.Abstractions\GridBot.Abstractions.csproj" />
  </ItemGroup>

  <ItemGroup>
    <!-- Dependencies for configuration and dependency injection -->
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="10.0.0-*" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="10.0.0-*" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.0-*" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="10.0.0-*" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.0-*" />
    <PackageReference Include="Microsoft.Extensions.Options" Version="10.0.0-*" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="10.0.0-*" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="10.0.0-*" />
  </ItemGroup>

  <ItemGroup>
    <!-- Copy native libraries to output directory -->
	  <None Include="Native\lighter-signer-windows-amd64.dll">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		  <Link>Native\lighter-signer-windows-amd64.dll</Link>
	  </None>

	  <None Include="Native\signer-arm64.so">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		  <Link>Native\signer-arm64.so</Link>
	  </None>
  </ItemGroup>

</Project>
